{{ config(materialized = 'table') }}

WITH ORDER_LOGISTICS AS (
    SELECT
        L.LOGISTICS_ID,
        L.COMPANY_NAME,
        L.SERVICE_TYPE
    FROM
        {{ ref('stg_logistics') }} L
), PRODUCT_PERFORMANCE AS (
    SELECT
        CI.CART_ID,
        COUNT(DISTINCT CI.PRODUCT_ID) AS UNIQUE_PRODUCTS_PER_ORDER,
        SUM(CI.QUANTITY) AS TOTAL_ITEMS_PER_ORDER,
        SUM(CI.LINE_TOTAL) AS TOTAL_ORDER_VALUE
    FROM
        {{ ref('int_cart_items') }} CI
    GROUP BY
        CI.CART_ID
), ORDER_DETAILS AS (
    SELECT
        C.CART_ID,
        C.CUSTOMER_ID,
        C.STATUS AS ORDER_STATUS,
        C.CREATED_AT AS ORDER_DATE,
        C.CART_TOTAL AS ORDER_VALUE
    FROM
        {{ ref('stg_carts') }} C
)
SELECT
    OD.*,
    PP.UNIQUE_PRODUCTS_PER_ORDER,
    PP.TOTAL_ITEMS_PER_ORDER,
    PP.TOTAL_ORDER_VALUE,
    (OD.ORDER_VALUE / NULLIF(PP.TOTAL_ITEMS_PER_ORDER, 0))::DECIMAL(10, 2) AS AVG_ITEM_VALUE
FROM
    ORDER_DETAILS OD
    LEFT JOIN PRODUCT_PERFORMANCE PP
    ON OD.CART_ID = PP.CART_ID
    LEFT JOIN ORDER_LOGISTICS OL
    ON OD.CART_ID = OL.LOGISTICS_ID