default:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgresdb
      user: postgres
      password: postgres
      port: 5432
      dbname: ecommerce
      schema: public
      threads: 4
